# Generated by Django 2.2.6 on 2025-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerledger_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
