# Generated by Django 2.2.6 on 2025-06-28 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20250617_1654'),
        ('product', '0011_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=65, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('shop_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoice_purchased', to='sales.ShopInvoice')),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_purchased_item', to='product.ShopProduct')),
            ],
        ),
    ]
