# Generated by Django 2.2.6 on 2025-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_shoppurchaseditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstockin',
            name='pack_quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopstockin',
            name='pack_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
