# Generated by Django 2.2.6 on 2025-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20250701_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopstockin',
            old_name='pack_quantity',
            new_name='bulk_quantity_quantity',
        ),
        migrations.AddField(
            model_name='shopstockin',
            name='number_of_parcel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopstockin',
            name='parcel_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
