# Generated by Django 2.2.6 on 2025-06-10 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerledger_invoice'),
        ('banking_system', '0007_auto_20191111_1628'),
        ('sales', '0007_auto_20201123_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInvoiceInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoice_installment', to='sales.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ShopInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Installment', 'Installment'), ('Check', 'Check')], default='Cash', max_length=100)),
                ('total_quantity', models.CharField(blank=True, default=1, max_length=10, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('remaining_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('cash_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('cash_returned', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_bank_detail_payments', to='banking_system.Bank')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_customer_sales', to='customer.Customer')),
            ],
        ),
    ]
