# Generated by Django 2.2.6 on 2025-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_shopinvoice_shopinvoiceinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
