# Generated by Django 2.2.6 on 2025-06-14 16:00

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoice_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=sales.models.barcode_upload_path),
        ),
    ]
