# Generated by Django 2.2.6 on 2025-06-17 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_invoice_check', models.BooleanField(default=False)),
                ('store_invoice_check', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('shop_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoice_checker', to='sales.Invoice')),
                ('store_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_invoice_checker', to='sales.Invoice')),
            ],
        ),
    ]
