# Generated by Django 2.2.6 on 2025-06-17 11:54

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_billchecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinvoice',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shopinvoice',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=sales.models.barcode_upload_path),
        ),
        migrations.AlterField(
            model_name='billchecker',
            name='shop_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoice_checker', to='sales.Invoice'),
        ),
        migrations.AlterField(
            model_name='billchecker',
            name='store_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_invoice_checker', to='sales.Invoice'),
        ),
    ]
