# Generated by Django 2.2.6 on 2025-08-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20250617_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billchecker',
            name='shop_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoice_checker', to='sales.ShopInvoice'),
        ),
    ]
